# Generated by Django 3.2.9 on 2021-11-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_comment_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
